// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  owner: __t.identity(),
  kind: __t.u8(),
  hp: __t.u32(),
  cooldown: __t.f32(),
  rallyX: __t.f32().name("rally_x"),
  rallyY: __t.f32().name("rally_y"),
  matchId: __t.u64().name("match_id"),
});
