// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.4.1 (commit 07b52763c9da8d7cf79780db222fec1ffcb84070).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddAiReducer from "./add_ai_reducer";
import AttackUnitReducer from "./attack_unit_reducer";
import AutoGatherReducer from "./auto_gather_reducer";
import CreateMatchReducer from "./create_match_reducer";
import DebugBigMatchReducer from "./debug_big_match_reducer";
import DebugStressReducer from "./debug_stress_reducer";
import DebugStressClearReducer from "./debug_stress_clear_reducer";
import DeleteSaveReducer from "./delete_save_reducer";
import DemolishBuildingReducer from "./demolish_building_reducer";
import EnterGameReducer from "./enter_game_reducer";
import GarrisonUnitReducer from "./garrison_unit_reducer";
import GatherResourceReducer from "./gather_resource_reducer";
import LeaveGameReducer from "./leave_game_reducer";
import LoadMatchReducer from "./load_match_reducer";
import MarketTradeReducer from "./market_trade_reducer";
import MoveUnitReducer from "./move_unit_reducer";
import PauseMatchReducer from "./pause_match_reducer";
import PlaceBuildingReducer from "./place_building_reducer";
import PlaceWallReducer from "./place_wall_reducer";
import ResumeMatchReducer from "./resume_match_reducer";
import SaveMatchReducer from "./save_match_reducer";
import SetRallyReducer from "./set_rally_reducer";
import SetStanceReducer from "./set_stance_reducer";
import StartResearchReducer from "./start_research_reducer";
import StartSkirmishReducer from "./start_skirmish_reducer";
import TrainUnitReducer from "./train_unit_reducer";
import UngarrisonBuildingReducer from "./ungarrison_building_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AiRow from "./ai_table";
import BuildingRow from "./building_table";
import ConfigRow from "./config_table";
import EntityRow from "./entity_table";
import GarrisonRow from "./garrison_table";
import MatchRow from "./match_table";
import PlayerRow from "./player_table";
import ResearchRow from "./research_table";
import ResourceNodeRow from "./resource_node_table";
import SaveSlotRow from "./save_slot_table";
import ShotRow from "./shot_table";
import TickCountRow from "./tick_count_table";
import UnitRow from "./unit_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  ai: __table(
    {
      name: "ai",
      indexes: [
        {
          accessor: "host",
          name: "ai_host_idx_btree",
          algorithm: "btree",
          columns: ["host"],
        },
        {
          accessor: "identity",
          name: "ai_identity_idx_btree",
          algorithm: "btree",
          columns: ["identity"],
        },
        {
          accessor: "matchId",
          name: "ai_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
      ],
      constraints: [
        {
          name: "ai_identity_key",
          constraint: "unique",
          columns: ["identity"],
        },
      ],
    },
    AiRow,
  ),
  building: __table(
    {
      name: "building",
      indexes: [
        {
          accessor: "entityId",
          name: "building_entity_id_idx_btree",
          algorithm: "btree",
          columns: ["entityId"],
        },
        {
          accessor: "matchId",
          name: "building_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
        {
          accessor: "owner",
          name: "building_owner_idx_btree",
          algorithm: "btree",
          columns: ["owner"],
        },
      ],
      constraints: [
        {
          name: "building_entity_id_key",
          constraint: "unique",
          columns: ["entityId"],
        },
      ],
    },
    BuildingRow,
  ),
  config: __table(
    {
      name: "config",
      indexes: [
        {
          accessor: "id",
          name: "config_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        { name: "config_id_key", constraint: "unique", columns: ["id"] },
      ],
    },
    ConfigRow,
  ),
  entity: __table(
    {
      name: "entity",
      indexes: [
        {
          accessor: "cell",
          name: "entity_cell_idx_btree",
          algorithm: "btree",
          columns: ["cell"],
        },
        {
          accessor: "entityId",
          name: "entity_entity_id_idx_btree",
          algorithm: "btree",
          columns: ["entityId"],
        },
        {
          accessor: "matchId",
          name: "entity_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
      ],
      constraints: [
        {
          name: "entity_entity_id_key",
          constraint: "unique",
          columns: ["entityId"],
        },
      ],
    },
    EntityRow,
  ),
  garrison: __table(
    {
      name: "garrison",
      indexes: [
        {
          accessor: "building",
          name: "garrison_building_idx_btree",
          algorithm: "btree",
          columns: ["building"],
        },
        {
          accessor: "slotId",
          name: "garrison_slot_id_idx_btree",
          algorithm: "btree",
          columns: ["slotId"],
        },
        {
          accessor: "unit",
          name: "garrison_unit_idx_btree",
          algorithm: "btree",
          columns: ["unit"],
        },
      ],
      constraints: [
        {
          name: "garrison_slot_id_key",
          constraint: "unique",
          columns: ["slotId"],
        },
        { name: "garrison_unit_key", constraint: "unique", columns: ["unit"] },
      ],
    },
    GarrisonRow,
  ),
  match: __table(
    {
      name: "match",
      indexes: [
        {
          accessor: "host",
          name: "match_host_idx_btree",
          algorithm: "btree",
          columns: ["host"],
        },
        {
          accessor: "matchId",
          name: "match_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
      ],
      constraints: [
        {
          name: "match_match_id_key",
          constraint: "unique",
          columns: ["matchId"],
        },
      ],
    },
    MatchRow,
  ),
  player: __table(
    {
      name: "player",
      indexes: [
        {
          accessor: "identity",
          name: "player_identity_idx_btree",
          algorithm: "btree",
          columns: ["identity"],
        },
        {
          accessor: "matchId",
          name: "player_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
        {
          accessor: "playerId",
          name: "player_player_id_idx_btree",
          algorithm: "btree",
          columns: ["playerId"],
        },
      ],
      constraints: [
        {
          name: "player_identity_key",
          constraint: "unique",
          columns: ["identity"],
        },
        {
          name: "player_player_id_key",
          constraint: "unique",
          columns: ["playerId"],
        },
      ],
    },
    PlayerRow,
  ),
  research: __table(
    {
      name: "research",
      indexes: [
        {
          accessor: "owner",
          name: "research_owner_idx_btree",
          algorithm: "btree",
          columns: ["owner"],
        },
        {
          accessor: "researchId",
          name: "research_research_id_idx_btree",
          algorithm: "btree",
          columns: ["researchId"],
        },
      ],
      constraints: [
        {
          name: "research_research_id_key",
          constraint: "unique",
          columns: ["researchId"],
        },
      ],
    },
    ResearchRow,
  ),
  resourceNode: __table(
    {
      name: "resource_node",
      indexes: [
        {
          accessor: "entityId",
          name: "resource_node_entity_id_idx_btree",
          algorithm: "btree",
          columns: ["entityId"],
        },
        {
          accessor: "matchId",
          name: "resource_node_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
      ],
      constraints: [
        {
          name: "resource_node_entity_id_key",
          constraint: "unique",
          columns: ["entityId"],
        },
      ],
    },
    ResourceNodeRow,
  ),
  saveSlot: __table(
    {
      name: "save_slot",
      indexes: [
        {
          accessor: "by_owner",
          name: "save_slot_owner_idx_btree",
          algorithm: "btree",
          columns: ["owner"],
        },
        {
          accessor: "by_owner_name",
          name: "save_slot_owner_name_idx_btree",
          algorithm: "btree",
          columns: ["owner", "name"],
        },
        {
          accessor: "saveId",
          name: "save_slot_save_id_idx_btree",
          algorithm: "btree",
          columns: ["saveId"],
        },
      ],
      constraints: [
        {
          name: "save_slot_save_id_key",
          constraint: "unique",
          columns: ["saveId"],
        },
      ],
    },
    SaveSlotRow,
  ),
  shot: __table(
    {
      name: "shot",
      indexes: [],
      constraints: [],
      event: true,
    },
    ShotRow,
  ),
  tickCount: __table(
    {
      name: "tick_count",
      indexes: [
        {
          accessor: "id",
          name: "tick_count_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        { name: "tick_count_id_key", constraint: "unique", columns: ["id"] },
      ],
    },
    TickCountRow,
  ),
  unit: __table(
    {
      name: "unit",
      indexes: [
        {
          accessor: "entityId",
          name: "unit_entity_id_idx_btree",
          algorithm: "btree",
          columns: ["entityId"],
        },
        {
          accessor: "matchId",
          name: "unit_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
        {
          accessor: "owner",
          name: "unit_owner_idx_btree",
          algorithm: "btree",
          columns: ["owner"],
        },
      ],
      constraints: [
        {
          name: "unit_entity_id_key",
          constraint: "unique",
          columns: ["entityId"],
        },
      ],
    },
    UnitRow,
  ),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_ai", AddAiReducer),
  __reducerSchema("attack_unit", AttackUnitReducer),
  __reducerSchema("auto_gather", AutoGatherReducer),
  __reducerSchema("create_match", CreateMatchReducer),
  __reducerSchema("debug_big_match", DebugBigMatchReducer),
  __reducerSchema("debug_stress", DebugStressReducer),
  __reducerSchema("debug_stress_clear", DebugStressClearReducer),
  __reducerSchema("delete_save", DeleteSaveReducer),
  __reducerSchema("demolish_building", DemolishBuildingReducer),
  __reducerSchema("enter_game", EnterGameReducer),
  __reducerSchema("garrison_unit", GarrisonUnitReducer),
  __reducerSchema("gather_resource", GatherResourceReducer),
  __reducerSchema("leave_game", LeaveGameReducer),
  __reducerSchema("load_match", LoadMatchReducer),
  __reducerSchema("market_trade", MarketTradeReducer),
  __reducerSchema("move_unit", MoveUnitReducer),
  __reducerSchema("pause_match", PauseMatchReducer),
  __reducerSchema("place_building", PlaceBuildingReducer),
  __reducerSchema("place_wall", PlaceWallReducer),
  __reducerSchema("resume_match", ResumeMatchReducer),
  __reducerSchema("save_match", SaveMatchReducer),
  __reducerSchema("set_rally", SetRallyReducer),
  __reducerSchema("set_stance", SetStanceReducer),
  __reducerSchema("start_research", StartResearchReducer),
  __reducerSchema("start_skirmish", StartSkirmishReducer),
  __reducerSchema("train_unit", TrainUnitReducer),
  __reducerSchema("ungarrison_building", UngarrisonBuildingReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures();

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.4.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> =
  __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(
  reducersSchema.reducersType.reducers,
);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<
  typeof REMOTE_MODULE
>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<
  typeof REMOTE_MODULE
>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<
  typeof REMOTE_MODULE
> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(
      REMOTE_MODULE,
      (config: __DbConnectionConfig<typeof REMOTE_MODULE>) =>
        new DbConnection(config),
    );
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
