// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  playerId: __t.u32().name("player_id"),
  name: __t.string(),
  faction: __t.u8(),
  wood: __t.u32(),
  stone: __t.u32(),
  food: __t.u32(),
  gold: __t.u32(),
  color: __t.u8(),
  online: __t.bool(),
  keepEntity: __t.u64().name("keep_entity"),
  defeated: __t.bool(),
  slot: __t.u8(),
  techMask: __t.u64().name("tech_mask"),
  matchId: __t.u64().name("match_id"),
});
