// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Ai = __t.object("Ai", {
  identity: __t.identity(),
  host: __t.identity(),
  difficulty: __t.u8(),
  decisionCd: __t.f32(),
  waveTimer: __t.f32(),
});
export type Ai = __Infer<typeof Ai>;

export const AiBrainTimer = __t.object("AiBrainTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AiBrainTimer = __Infer<typeof AiBrainTimer>;

export const AiTimer = __t.object("AiTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AiTimer = __Infer<typeof AiTimer>;

export const Building = __t.object("Building", {
  entityId: __t.u64(),
  owner: __t.identity(),
  kind: __t.u8(),
  hp: __t.u32(),
  cooldown: __t.f32(),
  rallyX: __t.f32(),
  rallyY: __t.f32(),
});
export type Building = __Infer<typeof Building>;

export const CombatTimer = __t.object("CombatTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CombatTimer = __Infer<typeof CombatTimer>;

export const Config = __t.object("Config", {
  id: __t.u32(),
  worldSize: __t.u32(),
  seed: __t.u32(),
  preset: __t.string(),
  initialized: __t.bool(),
  nextBotId: __t.u64(),
});
export type Config = __Infer<typeof Config>;

export const EconomyTimer = __t.object("EconomyTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type EconomyTimer = __Infer<typeof EconomyTimer>;

export const Entity = __t.object("Entity", {
  entityId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  facing: __t.f32(),
});
export type Entity = __Infer<typeof Entity>;

export const MoveTimer = __t.object("MoveTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MoveTimer = __Infer<typeof MoveTimer>;

export const PathPoint = __t.object("PathPoint", {
  x: __t.f32(),
  y: __t.f32(),
});
export type PathPoint = __Infer<typeof PathPoint>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  playerId: __t.u32(),
  name: __t.string(),
  faction: __t.u8(),
  wood: __t.u32(),
  stone: __t.u32(),
  food: __t.u32(),
  gold: __t.u32(),
  color: __t.u8(),
  online: __t.bool(),
  keepEntity: __t.u64(),
  defeated: __t.bool(),
  slot: __t.u8(),
});
export type Player = __Infer<typeof Player>;

export const ResourceNode = __t.object("ResourceNode", {
  entityId: __t.u64(),
  resType: __t.u8(),
  remaining: __t.u32(),
});
export type ResourceNode = __Infer<typeof ResourceNode>;

export const Shot = __t.object("Shot", {
  fromX: __t.f32(),
  fromY: __t.f32(),
  toX: __t.f32(),
  toY: __t.f32(),
});
export type Shot = __Infer<typeof Shot>;

export const Unit = __t.object("Unit", {
  entityId: __t.u64(),
  owner: __t.identity(),
  kind: __t.u8(),
  targetX: __t.f32(),
  targetY: __t.f32(),
  hasTarget: __t.bool(),
  speed: __t.f32(),
  gatherState: __t.u8(),
  targetNode: __t.u64(),
  carrying: __t.u32(),
  carryType: __t.u8(),
  harvestTimer: __t.f32(),
  hp: __t.u32(),
  attackTarget: __t.u64(),
  attackCooldown: __t.f32(),
  stance: __t.u8(),
  homeX: __t.f32(),
  homeY: __t.f32(),
  get path() {
    return __t.array(PathPoint);
  },
  pathIdx: __t.u32(),
});
export type Unit = __Infer<typeof Unit>;

export const WallTile = __t.object("WallTile", {
  x: __t.f32(),
  y: __t.f32(),
});
export type WallTile = __Infer<typeof WallTile>;

