// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PathPoint,
} from "./types";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  owner: __t.identity(),
  kind: __t.u8(),
  targetX: __t.f32().name("target_x"),
  targetY: __t.f32().name("target_y"),
  hasTarget: __t.bool().name("has_target"),
  speed: __t.f32(),
  gatherState: __t.u8().name("gather_state"),
  targetNode: __t.u64().name("target_node"),
  carrying: __t.u32(),
  carryType: __t.u8().name("carry_type"),
  harvestTimer: __t.f32().name("harvest_timer"),
  hp: __t.u32(),
  attackTarget: __t.u64().name("attack_target"),
  attackCooldown: __t.f32().name("attack_cooldown"),
  stance: __t.u8(),
  homeX: __t.f32().name("home_x"),
  homeY: __t.f32().name("home_y"),
  get path() {
    return __t.array(PathPoint);
  },
  pathIdx: __t.u32().name("path_idx"),
});
