// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAiReducer from "../add_ai_reducer";
import AttackUnitReducer from "../attack_unit_reducer";
import AutoGatherReducer from "../auto_gather_reducer";
import DemolishBuildingReducer from "../demolish_building_reducer";
import EnterGameReducer from "../enter_game_reducer";
import GatherResourceReducer from "../gather_resource_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import MoveUnitReducer from "../move_unit_reducer";
import PlaceBuildingReducer from "../place_building_reducer";
import PlaceWallReducer from "../place_wall_reducer";
import SetRallyReducer from "../set_rally_reducer";
import StartSkirmishReducer from "../start_skirmish_reducer";
import TrainUnitReducer from "../train_unit_reducer";

export type AddAiParams = __Infer<typeof AddAiReducer>;
export type AttackUnitParams = __Infer<typeof AttackUnitReducer>;
export type AutoGatherParams = __Infer<typeof AutoGatherReducer>;
export type DemolishBuildingParams = __Infer<typeof DemolishBuildingReducer>;
export type EnterGameParams = __Infer<typeof EnterGameReducer>;
export type GatherResourceParams = __Infer<typeof GatherResourceReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type MoveUnitParams = __Infer<typeof MoveUnitReducer>;
export type PlaceBuildingParams = __Infer<typeof PlaceBuildingReducer>;
export type PlaceWallParams = __Infer<typeof PlaceWallReducer>;
export type SetRallyParams = __Infer<typeof SetRallyReducer>;
export type StartSkirmishParams = __Infer<typeof StartSkirmishReducer>;
export type TrainUnitParams = __Infer<typeof TrainUnitReducer>;

