// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAiReducer from "../add_ai_reducer";
import AttackUnitReducer from "../attack_unit_reducer";
import AutoGatherReducer from "../auto_gather_reducer";
import CreateMatchReducer from "../create_match_reducer";
import DebugBigMatchReducer from "../debug_big_match_reducer";
import DebugStressReducer from "../debug_stress_reducer";
import DebugStressClearReducer from "../debug_stress_clear_reducer";
import DeleteSaveReducer from "../delete_save_reducer";
import DemolishBuildingReducer from "../demolish_building_reducer";
import EnterGameReducer from "../enter_game_reducer";
import GarrisonUnitReducer from "../garrison_unit_reducer";
import GatherResourceReducer from "../gather_resource_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import LoadMatchReducer from "../load_match_reducer";
import MarketTradeReducer from "../market_trade_reducer";
import MoveUnitReducer from "../move_unit_reducer";
import PauseMatchReducer from "../pause_match_reducer";
import PlaceBuildingReducer from "../place_building_reducer";
import PlaceWallReducer from "../place_wall_reducer";
import ResumeMatchReducer from "../resume_match_reducer";
import SaveMatchReducer from "../save_match_reducer";
import SetRallyReducer from "../set_rally_reducer";
import SetStanceReducer from "../set_stance_reducer";
import StartResearchReducer from "../start_research_reducer";
import StartSkirmishReducer from "../start_skirmish_reducer";
import TrainUnitReducer from "../train_unit_reducer";
import UngarrisonBuildingReducer from "../ungarrison_building_reducer";

export type AddAiParams = __Infer<typeof AddAiReducer>;
export type AttackUnitParams = __Infer<typeof AttackUnitReducer>;
export type AutoGatherParams = __Infer<typeof AutoGatherReducer>;
export type CreateMatchParams = __Infer<typeof CreateMatchReducer>;
export type DebugBigMatchParams = __Infer<typeof DebugBigMatchReducer>;
export type DebugStressParams = __Infer<typeof DebugStressReducer>;
export type DebugStressClearParams = __Infer<typeof DebugStressClearReducer>;
export type DeleteSaveParams = __Infer<typeof DeleteSaveReducer>;
export type DemolishBuildingParams = __Infer<typeof DemolishBuildingReducer>;
export type EnterGameParams = __Infer<typeof EnterGameReducer>;
export type GarrisonUnitParams = __Infer<typeof GarrisonUnitReducer>;
export type GatherResourceParams = __Infer<typeof GatherResourceReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type LoadMatchParams = __Infer<typeof LoadMatchReducer>;
export type MarketTradeParams = __Infer<typeof MarketTradeReducer>;
export type MoveUnitParams = __Infer<typeof MoveUnitReducer>;
export type PauseMatchParams = __Infer<typeof PauseMatchReducer>;
export type PlaceBuildingParams = __Infer<typeof PlaceBuildingReducer>;
export type PlaceWallParams = __Infer<typeof PlaceWallReducer>;
export type ResumeMatchParams = __Infer<typeof ResumeMatchReducer>;
export type SaveMatchParams = __Infer<typeof SaveMatchReducer>;
export type SetRallyParams = __Infer<typeof SetRallyReducer>;
export type SetStanceParams = __Infer<typeof SetStanceReducer>;
export type StartResearchParams = __Infer<typeof StartResearchReducer>;
export type StartSkirmishParams = __Infer<typeof StartSkirmishReducer>;
export type TrainUnitParams = __Infer<typeof TrainUnitReducer>;
export type UngarrisonBuildingParams = __Infer<
  typeof UngarrisonBuildingReducer
>;
